title: JaSON
description: JaSON Chrome Extension
google_analytics: 
show_downloads: false
logo: https://github.com/shanebell/JaSON/raw/master/public/jason-128x128.png
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
